### ISSUE TITLE
Removal of analytics

### ISSUE THREAD

**Issue by davidmpurdy** [B-Interactive/cloudflare-stream-wordpress#4]
I wanted to confirm my impression of the decision to remove analytics (050291562c74e929ed2199e4b9ac78f162084f3d). From what was being logged to Heap, I assume from what was being logged that these are for Cloudfront's usage and don't affect analytics on videos (i.e., the view for account holders, not Cloudflare corporate). Does that sound accurate?

**Comment by B-Interactive** [comment]
Initially I hesitated removing the analytics, as I suspect it's something Cloudflare would seek to retain in the official plugin.  However, my attempts to correct the confusing phrasing of the opt-in / opt-out control, were met with silence in a number of places where I reported it.  If my efforts were towards the official plugin, I would have handled this more conservatively and sought to clarify the ambiguities, not remove them entirely.

More to your query though, I'm not completely sure what the purpose of the analytics is, but my understanding is much as yours is; that this is data collected only for Cloudflare's purposes.

My general approach to collecting user data is: the less I know, the less I'm responsible for.  I don't need to disclaim, provide policies, or secure and protect, for that which I haven't collected.  That simplifies dealing with GPDR and similar.  Given the ambiguities of the feature, I decided to remove it.

That said, as it's an opt-in / opt-out option, I see no issue with re-introducing it (with corrected phrasing), if it has a function that benefits us.

**Comment by B-Interactive** [comment]
Having a look at when [logEvent is called](https://github.com/cloudflare/stream-wordpress/search?q=logEvent), it appears to be logging basic events related to administrative tasks (accessing plugin settings, uploading videos, completed upload, errors, etc).

**Comment by davidmpurdy** [comment]
Sounds like we're on the same page. I agree that it looks like internal analytics on usage and such -- but hopefully Cloudflare will weigh in.

**Comment by B-Interactive** [comment]
Thanks @davidmpurdy  for reaching out to Cloudflare to confirm this.  Cloudflare has confirmed that Heaps analytics is EoL and should be removed.

I'll close the issue as such.
