### ISSUE TITLE
add custom player

### ISSUE THREAD

**Issue by oecin** [B-Interactive/cloudflare-stream-wordpress#42]
Can I use a custom player? I don't want to display the view count.

Thank you.

**Comment by B-Interactive** [comment]
Just to clarify, are you seeing a view count on the Cloudflare player?

![image](https://github.com/user-attachments/assets/7504084c-6bd2-4e90-a792-573343d249b4)

With respect to a custom player, [I had explored this option a while ago](https://github.com/B-Interactive/cloudflare-stream-wordpress/issues/6#issuecomment-1225095333), specifically using [Video.js](https://github.com/videojs/video.js).  I had considered providing it as an alternative player option.

In the end, I shelved those efforts, as the benefit wasn't at all obvious, yet it would certainly introduce maintenance upkeep.

Is there a reason you're not satisfied with the Cloudflare player?

**Comment by oecin** [comment]
becase if use  Cloudflare live steam  it will show

 Cloudflare video will not show

you can check it

**Comment by B-Interactive** [comment]
Ah, thank you for clarifying that.  As you rightly noted, I was investigating with a non-live video.

Looking to Stream Live docs though, I can see the ability to hide live viewer count is also supported.  It's an API parameter you can specify.

See here (look for `hideLiveViewerCount` ):
https://developers.cloudflare.com/stream/stream-live/start-stream-live/

This example has the `hideLiveViewerCount` parameter defined as `true`:

```
curl -X POST \
--header "Authorization: Bearer <API_TOKEN>" \
--data '{"meta": {"name":"test stream"},"recording": { "mode": "automatic", "hideLiveViewerCount": true }}' \
https://api.cloudflare.com/client/v4/accounts/{account_id}/stream/live_inputs
```

Will that serve your needs?
