### ISSUE TITLE
Upgrade path for existing blocks

### ISSUE THREAD

**Issue by davidmpurdy** [B-Interactive/cloudflare-stream-wordpress#5]
We probably have updates coming that will affect blocks created with the current/old versions of the plugin:
* Using the new iframe player. #6 
* Adding signed URLs (setting videos to require signed URLs would break existing blocks that don't have that capability). #3 

Some ideas to mitigate this:

1. Add a render callback for old blocks to intercept the current markup and output something new. Feels like it's probably the easiest to implement but to keep it working we have to keep supporting that existing block markup indefinitely.
2. Write an upgrade process to search through existing posts containing the current block and update them in each post's source. I've written background routines before and it's always been kind of a pain. This might be the cleanest going forwards, but it feels like a lot of work to implement well. 
3. Make a new major version that just breaks existing blocks if signed URLs are enforced for a video or the old player ever stops working. This is kind of the default of what would happen to existing blocks anyway. This fits my personal use case, but if we want this to serve a wider user base might not be the friendliest if there are folx with a ton of existing videos. 

I'm open to thoughts on how to approach this.

**Comment by B-Interactive** [comment]
Of those options, I'm personally leaning towards number 2, but based on your description, it may involve the most work.

I've not personally had to write routines of that sort, but if I can be of assistance, I'm happy to get my hands dirty.  Perhaps once the new block is closer to completion, we'll have a clearer picture of which option is most appropriate and how to approach it.

**Comment by davidmpurdy** [comment]
After poking around a bit, there is actually an elegantly simple answer: [block deprecations](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-deprecation/). Makes my massive block upgrade PR a little more complicated, but is undoubtedly the right answer.

**Comment by B-Interactive** [comment]
Nice find, that's perfect! :+1:
