### ISSUE TITLE
Upload button is missing

### ISSUE THREAD

**Issue by davidmpurdy** [B-Interactive/cloudflare-stream-wordpress#9]
Looks like I broke the upload button didn't come in with my block fix. Probably because I based my solution on previous work that didn't incorporate the API token improvement, and the block uses API credentials to directly upload files via tus. 

Working on a fix to send the token/zone instead of the key/account/email to the block script and change the base URL appropriately within the block.

**Comment by davidmpurdy** [comment]
OK, I think it's working, but there's an error after upload that I _think_ has to do with the block still using the legacy player. Unless there's an objection, I think I'll just roll it into a PR to fix/update the block so I can test it all together instead of little piecemeal updates, each with something broken in them. While we're cleaning house and updating, bigger PRs that just fix problems feels like the approach to me.

**Comment by B-Interactive** [comment]
Hey no worries @davidmpurdy.  Just give me a heads up if you're planning any big changes to [class-cloudflare-stream-api.php](https://github.com/B-Interactive/cloudflare-stream-wordpress/blob/main/src/inc/class-cloudflare-stream-api.php), or [class-cloudflare-stream-settings.php](https://github.com/B-Interactive/cloudflare-stream-wordpress/blob/main/src/inc/class-cloudflare-stream-settings.php), as that's where my attention has mostly been.
